services:
  postgres:
    image: postgres:14
    container_name: nimbuslance_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nimbuslance
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ../apps/backend
    env_file:
      - ../apps/backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: npm run start:dev
    volumes:
      - ../apps/backend:/app
      - /app/node_modules

volumes:
  postgres_data: